clinical_protocols = [
    {'id': 1, 'protocol': 'P-001', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Cardiology follow-up for Stage 2 Hypertension patients with lead time exceeding 14 days'},
    {'id': 2, 'protocol': 'P-002', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Diabetic retinopathy screening for Type 2 Diabetes patients with A1C above 8 percent'},
    {'id': 3, 'protocol': 'P-003', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Prenatal care for first-time mothers with transport dependency in urban zones'},
    {'id': 4, 'protocol': 'P-004', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Pediatric immunization schedule tracking with parental reminder protocol v2'},
    {'id': 5, 'protocol': 'P-005', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'COPD management for patients requiring oxygen transport assistance services'},
    {'id': 6, 'protocol': 'P-006', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'General wellness checkup for patients aged 35 to 60 with no comorbidities'},
    {'id': 7, 'protocol': 'P-007', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Chronic Kidney Disease stage 3 nephrology follow-up with lab pre-authorization'},
    {'id': 8, 'protocol': 'P-008', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Major Depressive Disorder psychiatric consultation with social support screening'},
    {'id': 9, 'protocol': 'P-009', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Generalized Anxiety Disorder CBT session scheduling with telehealth option'},
    {'id': 10, 'protocol': 'P-010', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Bipolar Disorder mood stabilizer titration with pharmacy integration check'},
    {'id': 11, 'protocol': 'P-011', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Osteoarthritis pain management with mobility transport assistance for elderly'},
    {'id': 12, 'protocol': 'P-012', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Coronary Artery Disease stress test with manual call mandatory for high risk'},
    {'id': 13, 'protocol': 'P-013', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Post-stroke recovery physical and occupational therapy caregiver coordination'},
    {'id': 14, 'protocol': 'P-014', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Oncology chemotherapy response monitoring with extreme fatigue management'},
    {'id': 15, 'protocol': 'P-015', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'HIV antiretroviral therapy adherence with stigma-free privacy protocol'},
    {'id': 16, 'protocol': 'P-016', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Class III obesity bariatric nutrition counseling with transport accommodation'},
    {'id': 17, 'protocol': 'P-017', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Alzheimer early stage memory care monitoring with caregiver contact alert'},
    {'id': 18, 'protocol': 'P-018', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Parkinson disease neurological motor assessment with tremor accommodation'},
    {'id': 19, 'protocol': 'P-019', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Epilepsy seizure frequency tracking with driving restriction ride-share coordination'},
    {'id': 20, 'protocol': 'P-020', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Inflammatory Bowel Disease gastroenterology follow-up with flare management'},
    {'id': 21, 'protocol': 'P-021', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Severe Psoriasis dermatological biologics scheduling with self-esteem support'},
    {'id': 22, 'protocol': 'P-022', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Sleep Apnea CPAP usage review with day-time sleepiness driving safety check'},
    {'id': 23, 'protocol': 'P-023', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Thyroid Disorder endocrine labs with brain fog cognitive assistance protocol'},
    {'id': 24, 'protocol': 'P-024', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Osteoporosis bone density scan with fracture-risk transport safety assessment'},
    {'id': 25, 'protocol': 'P-025', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Acute Gout flare rheumatology consult with immobility management plan'},
    {'id': 26, 'protocol': 'P-026', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Macular Degeneration ophthalmology injections with clinic navigation support'},
    {'id': 27, 'protocol': 'P-027', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Annual wellness physical for adults aged 18 to 35 with digital-first approach'},
    {'id': 28, 'protocol': 'P-028', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Post-COVID long-haul syndrome multidisciplinary follow-up with fatigue scoring'},
    {'id': 29, 'protocol': 'P-029', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Pediatric asthma management with school nurse coordination and inhaler tracking'},
    {'id': 30, 'protocol': 'P-030', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Geriatric fall prevention assessment with physical therapy and home visit option'},
    {'id': 31, 'protocol': 'P-031', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Celiac disease dietary adherence review with registered dietitian consultation'},
    {'id': 32, 'protocol': 'P-032', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Lupus flare management with rheumatology urgent slot prioritization protocol'},
    {'id': 33, 'protocol': 'P-033', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Iron deficiency anemia follow-up with IV infusion scheduling and transport'},
    {'id': 34, 'protocol': 'P-034', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Seasonal allergy immunotherapy appointment with medication timing alignment'},
    {'id': 35, 'protocol': 'P-035', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Liver cirrhosis hepatology monitoring with ascites fluid management protocol'},
    {'id': 36, 'protocol': 'P-036', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Sickle cell disease hematology follow-up with pain crisis emergency protocol'},
    {'id': 37, 'protocol': 'P-037', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Migraine neurology follow-up with triptan efficacy assessment and lifestyle review'},
    {'id': 38, 'protocol': 'P-038', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Menopause hormone therapy review with endocrinology consultation scheduling'},
    {'id': 39, 'protocol': 'P-039', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Pediatric growth monitoring with nutrition assessment and developmental screening'},
    {'id': 40, 'protocol': 'P-040', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Pulmonary fibrosis respiratory therapy with oxygen level home monitoring setup'},
    {'id': 41, 'protocol': 'P-041', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Routine dermatology skin check for fair-skinned patients with sun exposure risk'},
    {'id': 42, 'protocol': 'P-042', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Post-bariatric surgery nutritional follow-up with supplement adherence tracking'},
    {'id': 43, 'protocol': 'P-043', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Organ transplant recipient immunosuppression monitoring with lab frequency rules'},
    {'id': 44, 'protocol': 'P-044', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'ADHD medication management pediatric and adult follow-up with school liaison'},
    {'id': 45, 'protocol': 'P-045', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Sepsis recovery follow-up with infection specialist and wound care coordination'},
    {'id': 46, 'protocol': 'P-046', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Dental health integration with primary care for diabetic patients A1C correlation'},
    {'id': 47, 'protocol': 'P-047', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Alcohol use disorder treatment follow-up with support group coordination'},
    {'id': 48, 'protocol': 'P-048', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Opioid addiction recovery MAT program with weekly check-in and urine screening'},
    {'id': 49, 'protocol': 'P-049', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Schizophrenia long-acting injectable antipsychotic scheduling with social worker'},
    {'id': 50, 'protocol': 'P-050', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'PTSD trauma therapy with veteran-specific outreach and flexible appointment model'},
    {'id': 51, 'protocol': 'P-051', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Urgent care post-visit follow-up within 72 hours for discharged high-risk patients'},
    {'id': 52, 'protocol': 'P-052', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Chronic pain management multidisciplinary panel review with opioid stewardship'},
    {'id': 53, 'protocol': 'P-053', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Vision screening for children aged 3 to 6 years with school entry coordination'},
    {'id': 54, 'protocol': 'P-054', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Hearing assessment for patients over 65 with hearing aid fitting referral'},
    {'id': 55, 'protocol': 'P-055', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Congestive Heart Failure fluid management with daily weight monitoring alert'},
    {'id': 56, 'protocol': 'P-056', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Deep vein thrombosis anticoagulation monitoring with INR weekly lab schedule'},
    {'id': 57, 'protocol': 'P-057', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Glaucoma ophthalmology pressure check with visual field testing bi-annual'},
    {'id': 58, 'protocol': 'P-058', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Pre-conception counseling for couples with genetic risk factor screening'},
    {'id': 59, 'protocol': 'P-059', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Neonatal jaundice follow-up within 24 hours post-discharge with home phototherapy'},
    {'id': 60, 'protocol': 'P-060', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Eczema atopic dermatitis management with allergen panel and topical therapy review'},
    {'id': 61, 'protocol': 'P-061', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Acute pancreatitis gastroenterology follow-up with enzyme level monitoring protocol'},
    {'id': 62, 'protocol': 'P-062', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Fibromyalgia rheumatology follow-up with physical therapy and pain diary review'},
    {'id': 63, 'protocol': 'P-063', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Health coaching session for lifestyle modification and preventive care planning'},
    {'id': 64, 'protocol': 'P-064', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Amputation post-surgical wound care with prosthetist coordination and PT referral'},
    {'id': 65, 'protocol': 'P-065', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Cystic fibrosis pulmonology follow-up with respiratory therapist co-management'},
    {'id': 66, 'protocol': 'P-066', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Multiple sclerosis neurology follow-up with MRI scheduling and infusion coordination'},
    {'id': 67, 'protocol': 'P-067', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Rheumatoid arthritis biologic infusion scheduling with infection risk screening'},
    {'id': 68, 'protocol': 'P-068', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Smoking cessation counseling with nicotine replacement therapy follow-up'},
    {'id': 69, 'protocol': 'P-069', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Peritoneal dialysis peritonitis follow-up with nephrology emergency escalation'},
    {'id': 70, 'protocol': 'P-070', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Spinal stenosis neurosurgery evaluation with conservative therapy trial period'},
    {'id': 71, 'protocol': 'P-071', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Acute leukemia induction chemotherapy monitoring with blood count daily tracking'},
    {'id': 72, 'protocol': 'P-072', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Preventive colonoscopy for adults over 45 with bowel prep instruction portal'},
    {'id': 73, 'protocol': 'P-073', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Heel pain plantar fasciitis podiatry consultation with orthotics measurement'},
    {'id': 74, 'protocol': 'P-074', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Gestational diabetes monitoring with bi-weekly OB and dietitian coordination'},
    {'id': 75, 'protocol': 'P-075', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Vascular disease peripheral artery follow-up with ankle-brachial index review'},
    {'id': 76, 'protocol': 'P-076', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Seasonal flu vaccine administration campaign targeting high-risk cohort patients'},
    {'id': 77, 'protocol': 'P-077', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Uterine fibroid gynecology follow-up with hormonal therapy options review'},
    {'id': 78, 'protocol': 'P-078', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Breast cancer follow-up surveillance with imaging and oncology panel review'},
    {'id': 79, 'protocol': 'P-079', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Prostate cancer active surveillance with PSA monitoring quarterly schedule'},
    {'id': 80, 'protocol': 'P-080', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Colorectal cancer post-surgery follow-up with CEA level and imaging schedule'},
    {'id': 81, 'protocol': 'P-081', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Sports medicine injury follow-up with physiotherapy milestones and return-to-play'},
    {'id': 82, 'protocol': 'P-082', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Weight management program 3-month check-in with dietitian and exercise specialist'},
    {'id': 83, 'protocol': 'P-083', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Severe COVID-19 ICU post-discharge pulmonary rehabilitation program coordination'},
    {'id': 84, 'protocol': 'P-084', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Hypothyroidism TSH monitoring with endocrinology dosage adjustment protocol'},
    {'id': 85, 'protocol': 'P-085', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Nutrition counseling for pediatric obesity with family lifestyle modification plan'},
    {'id': 86, 'protocol': 'P-086', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Acute myocardial infarction 30-day cardiology follow-up with rehab enrolment'},
    {'id': 87, 'protocol': 'P-087', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Endometriosis gynecology management with laparoscopy surgical consultation'},
    {'id': 88, 'protocol': 'P-088', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Pediatric appendectomy post-surgical follow-up with incision site monitoring'},
    {'id': 89, 'protocol': 'P-089', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Hyponatremia nephrology electrolyte management with dietary sodium review'},
    {'id': 90, 'protocol': 'P-090', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Annual eye exam for contact lens users with refraction update and pressure check'},
    {'id': 91, 'protocol': 'P-091', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Hidradenitis suppurativa dermatology follow-up with biologic or surgical option'},
    {'id': 92, 'protocol': 'P-092', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Septic shock 7-day post-discharge infection disease follow-up with wound check'},
    {'id': 93, 'protocol': 'P-093', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Autism spectrum disorder developmental pediatrics follow-up with IEP coordination'},
    {'id': 94, 'protocol': 'P-094', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Acute kidney injury 14-day renal recovery monitoring with creatinine trending'},
    {'id': 95, 'protocol': 'P-095', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Speech therapy post-stroke aphasia rehab with caregiver instruction and home plan'},
    {'id': 96, 'protocol': 'P-096', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Routine Pap smear cervical cancer screening with HPV co-test option reminder'},
    {'id': 97, 'protocol': 'P-097', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Abdominal aortic aneurysm vascular surgery surveillance with imaging schedule'},
    {'id': 98, 'protocol': 'P-098', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Interstitial lung disease pulmonology follow-up with 6-minute walk test scoring'},
    {'id': 99, 'protocol': 'P-099', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Diabetic neuropathy pain management with neurology consultation and TENS therapy'},
    {'id': 100, 'protocol': 'P-100', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Critical care ICU delirium recovery follow-up with cognitive rehabilitation team'},
    {'id': 101, 'protocol': 'P-101', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Risk stratification for no-show prediction model inference pipeline v1'},
    {'id': 102, 'protocol': 'P-102', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Feature engineering pipeline with lead time, age and comorbidity factor weighting'},
    {'id': 103, 'protocol': 'P-103', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'FAISS vector store retrieval for top-k matching clinical guideline context'},
    {'id': 104, 'protocol': 'P-104', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Groq LLM inference call wrapper with exponential retry and timeout handling'},
    {'id': 105, 'protocol': 'P-105', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'LangGraph state graph node registration for multi-step care report generation'},
    {'id': 106, 'protocol': 'P-106', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Session state persistence logic for Streamlit multi-tab prediction caching'},
    {'id': 107, 'protocol': 'P-107', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'PDF report layout engine with fpdf2 multi-cell wrapping and logo placement'},
    {'id': 108, 'protocol': 'P-108', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Data schema validation for uploaded appointment CSV with missing column alerts'},
    {'id': 109, 'protocol': 'P-109', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Sample data download button in sidebar for demo mode without real patient data'},
    {'id': 110, 'protocol': 'P-110', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Risk level cut categorization using probability bins for Low Medium and High labels'},
    {'id': 111, 'protocol': 'P-111', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Altair bar chart rendering for risk distribution with custom color scale encoding'},
    {'id': 112, 'protocol': 'P-112', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Feature importance horizontal bar chart from XGBoost model feature names in array'},
    {'id': 113, 'protocol': 'P-113', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Patient risk table sortable by probability with progress column config in dataframe'},
    {'id': 114, 'protocol': 'P-114', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Agent state dict construction with patient_data risk_summary and final_report keys'},
    {'id': 115, 'protocol': 'P-115', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Intervention strategy expander with emoji badge priority system in report view'},
    {'id': 116, 'protocol': 'P-116', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Ethical disclaimer and operational disclaimer rendering in care coordinator tab'},
    {'id': 117, 'protocol': 'P-117', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Model loading with joblib cache decorator for performance on repeated inference'},
    {'id': 118, 'protocol': 'P-118', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Build FAISS index from sentence transformer embeddings for care guidelines text'},
    {'id': 119, 'protocol': 'P-119', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'RAG context retrieval using cosine similarity with top-3 document chunk return'},
    {'id': 120, 'protocol': 'P-120', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'LangGraph conditional edge routing based on error presence in agent state dict'},
    {'id': 121, 'protocol': 'P-121', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'dotenv configuration loading for GROQ_API_KEY with secrets.toml fallback'},
    {'id': 122, 'protocol': 'P-122', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Preprocessing date columns into LeadTime feature with negative clip to zero'},
    {'id': 123, 'protocol': 'P-123', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'On-call SMS verification rate aggregation per patient cohort for agent context'},
    {'id': 124, 'protocol': 'P-124', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Age-based comorbidity segmentation for patient cohort narrative generation'},
    {'id': 125, 'protocol': 'P-125', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Spinner loading state for long-running agent invocation in care coordinator tab'},
    {'id': 126, 'protocol': 'P-126', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'FAISS index file persistence to disk with pkl metadata storage for reuse'},
    {'id': 127, 'protocol': 'P-127', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Report sources citation rendering as numbered list from agent JSON response'},
    {'id': 128, 'protocol': 'P-128', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'PDF binary download button with care_coordination_report.pdf default filename'},
    {'id': 129, 'protocol': 'P-129', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Streamlit page config with Clinical No-Show Predictor title and wide layout mode'},
    {'id': 130, 'protocol': 'P-130', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'No-show risk summary info box with high-risk patient count from prediction output'},
    {'id': 131, 'protocol': 'P-131', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Final agent state validation with error key check before report display rendering'},
    {'id': 132, 'protocol': 'P-132', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'FAISS build pipeline with chunk splitting and overlap for large guideline files'},
    {'id': 133, 'protocol': 'P-133', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Appointment data uploader with CSV type enforcement and multi-patient batch mode'},
    {'id': 134, 'protocol': 'P-134', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Full preprocessing output column alignment with trained model feature_names_in_'},
    {'id': 135, 'protocol': 'P-135', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Colour blind safe palette for risk level charts using accessible hex color values'},
    {'id': 136, 'protocol': 'P-136', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Clinical no-show care report title heading with subtitle in PDF first page layout'},
    {'id': 137, 'protocol': 'P-137', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Overview dashboard metric cards total high medium and low risk patient counts'},
    {'id': 138, 'protocol': 'P-138', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Dataframe display column config with progress bar for probability value rendering'},
    {'id': 139, 'protocol': 'P-139', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Deterministic agent state machine with START to risk_summary to retrieve to report'},
    {'id': 140, 'protocol': 'P-140', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Multi-source evidence synthesis in LLM prompt for generating structured JSON report'},
    {'id': 141, 'protocol': 'P-141', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Care guidelines text file reading and line splitting for FAISS chunk construction'},
    {'id': 142, 'protocol': 'P-142', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Groq ChatGroq client initialization with model llama-3.1-8b-instant and timeout'},
    {'id': 143, 'protocol': 'P-143', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Model predict_proba call with column selection and preprocessing before scoring'},
    {'id': 144, 'protocol': 'P-144', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Report section generation with badges for high medium and low priority strategies'},
    {'id': 145, 'protocol': 'P-145', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Intervention strategy JSON schema with strategy description and priority fields'},
    {'id': 146, 'protocol': 'P-146', 'status': 'ACTIVE', 'priority': 'MEDIUM', 'desc': 'Patient data dict construction from prediction dataframe for agent input context'},
    {'id': 147, 'protocol': 'P-147', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Care coordinator tab rendering conditional on ML predictions tab completion first'},
    {'id': 148, 'protocol': 'P-148', 'status': 'ACTIVE', 'priority': 'LOW', 'desc': 'Requirements.txt pin versions for reproducible environment across all deployments'},
    {'id': 149, 'protocol': 'P-149', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'Sentence transformer model all-MiniLM-L6-v2 for guideline text vector encoding'},
    {'id': 150, 'protocol': 'P-150', 'status': 'ACTIVE', 'priority': 'HIGH', 'desc': 'XGBoost model serialization with joblib and storage in models directory for app'},
]

def get_protocol(pid):
    for item in clinical_protocols:
        if item['id'] == pid:
            return item
    return None

def list_all_protocols():
    return clinical_protocols

def filter_by_priority(level):
    return [p for p in clinical_protocols if p['priority'] == level]

def count_active():
    return sum(1 for p in clinical_protocols if p['status'] == 'ACTIVE')

def protocol_summary():
    return {
        'total': len(clinical_protocols),
        'high': len(filter_by_priority('HIGH')),
        'medium': len(filter_by_priority('MEDIUM')),
        'low': len(filter_by_priority('LOW')),
        'active': count_active()
    }
